[build]
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin/login.html"
  status = 301
  force = true

[[redirects]]
  from = "/kitchen"
  to = "/kitchen/kitchen.html"
  status = 301
  force = true

[[redirects]]
  from = "/waiter"
  to = "/kitchen/waiter.html"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/admin/dashboard.html"
  status = 301
  force = true